In [2]:
import pandas as pd
df=pd.read_csv(r"C:\Users\prodd\Downloads\df_final_demo.txt")

In [3]:
part1=pd.read_csv(r"C:\Users\prodd\Downloads\df_final_web_data_pt_1.txt")

In [4]:
part2=pd.read_csv(r"C:\Users\prodd\Downloads\df_final_web_data_pt_2.txt")

In [5]:
df_concated=pd.concat([part1,part2], ignore_index=True)

In [6]:
Variation=pd.read_csv(r"C:\Users\prodd\Downloads\df_final_experiment_clients.txt")

In [7]:
merged = pd.merge(df, df_concated, on='client_id', how='inner')

In [8]:
full_df = pd.merge(merged, Variation, on='client_id', how='inner')

In [9]:
full_df.shape

(449831, 14)

In [ ]:
full_df=full_df.drop_duplicates()

np.int64(0)

In [17]:
full_df = full_df[full_df["gendr"].isin(["M", "F"])]

In [20]:
full_df=full_df.dropna()

In [21]:
full_df.isna().sum()

client_id           0
clnt_tenure_yr      0
clnt_tenure_mnth    0
clnt_age            0
gendr               0
num_accts           0
bal                 0
calls_6_mnth        0
logons_6_mnth       0
visitor_id          0
visit_id            0
process_step        0
date_time           0
Variation           0
dtype: int64

In [ ]:
primary_cilents=full_df.groupby('client_id').agg({'visit_id': 'count'}).sort_values(by='visit_id',ascending=False).head(10)
primary_cilents

In [22]:
test_table=full_df[full_df['Variation'].str.lower() == 'test']
test_table

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth,visitor_id,visit_id,process_step,date_time,Variation
22,1562045,16.0,198.0,49.0,M,2.0,67454.65,3.0,6.0,391202328_71710993352,71954691_44810191073_495385,start,2017-04-06 19:03:46,Test
36,388801,30.0,361.0,57.5,M,5.0,522498.72,1.0,4.0,56607555_75044897582,247503697_11679931698_453228,confirm,2017-04-06 10:48:22,Test
37,388801,30.0,361.0,57.5,M,5.0,522498.72,1.0,4.0,56607555_75044897582,247503697_11679931698_453228,step_3,2017-04-06 10:45:09,Test
38,388801,30.0,361.0,57.5,M,5.0,522498.72,1.0,4.0,56607555_75044897582,247503697_11679931698_453228,step_2,2017-04-06 10:41:56,Test
39,388801,30.0,361.0,57.5,M,5.0,522498.72,1.0,4.0,56607555_75044897582,247503697_11679931698_453228,step_1,2017-04-06 10:39:23,Test
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
321304,7468138,18.0,222.0,61.0,F,3.0,209278.15,0.0,3.0,317123960_46820919455,769876461_30381166055_830233,step_2,2017-03-30 23:59:15,Test
321305,7468138,18.0,222.0,61.0,F,3.0,209278.15,0.0,3.0,317123960_46820919455,769876461_30381166055_830233,step_1,2017-03-30 23:58:51,Test
321306,7468138,18.0,222.0,61.0,F,3.0,209278.15,0.0,3.0,317123960_46820919455,769876461_30381166055_830233,start,2017-03-30 23:58:40,Test
321307,7468138,18.0,222.0,61.0,F,3.0,209278.15,0.0,3.0,317123960_46820919455,769876461_30381166055_830233,start,2017-03-30 23:55:11,Test
321308,7468138,18.0,222.0,61.0,F,3.0,209278.15,0.0,3.0,317123960_46820919455,769876461_30381166055_830233,start,2017-03-31 00:16:12,Test

In [23]:
control_table = full_df[full_df['Variation'].str.lower() == 'control']
control_table

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth,visitor_id,visit_id,process_step,date_time,Variation
23,5126305,12.0,145.0,33.0,F,2.0,103671.75,0.0,3.0,432077852_35036160885,942996157_39527225999_589383,start,2017-06-14 14:22:31,Control
41,285619,30.0,369.0,67.5,M,2.0,299388.72,3.0,6.0,667009768_32934260678,545534470_5635716155_93472,confirm,2017-03-29 11:57:25,Control
42,285619,30.0,369.0,67.5,M,2.0,299388.72,3.0,6.0,667009768_32934260678,545534470_5635716155_93472,step_3,2017-03-29 11:55:31,Control
43,285619,30.0,369.0,67.5,M,2.0,299388.72,3.0,6.0,667009768_32934260678,545534470_5635716155_93472,step_2,2017-03-29 11:55:27,Control
44,285619,30.0,369.0,67.5,M,2.0,299388.72,3.0,6.0,667009768_32934260678,545534470_5635716155_93472,step_3,2017-03-29 11:54:55,Control
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
321283,6967120,21.0,260.0,68.5,M,3.0,4279873.38,6.0,9.0,663474827_38847225720,923772865_74694577233_449836,confirm,2017-04-12 19:06:55,Control
321284,6967120,21.0,260.0,68.5,M,3.0,4279873.38,6.0,9.0,663474827_38847225720,923772865_74694577233_449836,step_3,2017-04-12 19:05:14,Control
321285,6967120,21.0,260.0,68.5,M,3.0,4279873.38,6.0,9.0,663474827_38847225720,923772865_74694577233_449836,step_2,2017-04-12 19:04:29,Control
321286,6967120,21.0,260.0,68.5,M,3.0,4279873.38,6.0,9.0,663474827_38847225720,923772865_74694577233_449836,step_1,2017-04-12 19:04:07,Control
321287,6967120,21.0,260.0,68.5,M,3.0,4279873.38,6.0,9.0,663474827_38847225720,923772865_74694577233_449836,start,2017-04-12 19:03:36,Control

In [28]:
test_table.duplicated().sum()

np.int64(0)

In [29]:
#test_table
completed_clients=test_table[test_table["process_step"]=="confirm"]["client_id"].nunique()
total_clients=test_table["client_id"].nunique()
completion_rate = completed_clients / total_clients
completion_rate

0.688294805855423

In [30]:
#control_table
completed_clients=control_table[control_table["process_step"]=="confirm"]["client_id"].nunique()
total_clients=control_table["client_id"].nunique()
completion_rate = completed_clients / total_clients
completion_rate

0.649561629706034

In [ ]:
# Time Spent on each step
# Step 1: Make a clean copy
test_table = test_table.copy()

# Step 2: Convert date_time in test_table, not merged
test_table['date_time'] = pd.to_datetime(test_table['date_time'], errors='coerce')

# Step 3: Sort and calculate time spent
sorted_test = test_table.sort_values(by=['visit_id', 'date_time'])

sorted_test['time_spent_minutes'] = (
    sorted_test.groupby('visit_id')['date_time']
    .diff()
    .abs()
    .dt.total_seconds() / 60
)

sorted_test['time_spent_minutes']
#diff() is difference between dates
#abs() convert -ve to +ve
#dt.total_seconds()/60 is to convert into minutes

78048          NaN
78047     0.266667
78046     0.150000
78045     0.233333
78044     0.100000
            ...
198806         NaN
198805    0.183333
198804    0.900000
198803    0.733333
198802    0.150000
Name: time_spent_minutes, Length: 117457, dtype: float64

In [32]:
sorted_test.groupby('visit_id')['time_spent_minutes'].sum()
# Total Time per Visit

visit_id
100019538_17884295066_43909      4.033333
100022086_87870757897_149620     3.000000
100173292_91322748906_143563     1.583333
100217156_67053490690_383412    16.950000
100221419_95702886123_228743     0.000000
                                  ...
999960019_60838685252_926860    28.483333
999971096_28827267783_236076     2.316667
999976049_95772503197_182554    12.133333
999984454_18731538378_781808     2.566667
999988789_76411676596_272843     1.966667
Name: time_spent_minutes, Length: 24820, dtype: float64

In [33]:
sorted_test.groupby('process_step')['time_spent_minutes'].mean()
#. Average Time per Step

process_step
confirm    2.221794
start      2.490461
step_1     0.649628
step_2     0.837010
step_3     1.617487
Name: time_spent_minutes, dtype: float64

In [ ]:
#Time spent on each step for control table
# Make a clean copy
control_table = control_table.copy()

# Step 2: Convert date_time in test_table, not merged
control_table['date_time'] = pd.to_datetime(control_table['date_time'], errors='coerce')

# Step 3: Sort and calculate time spent
sorted_control = control_table.sort_values(by=['visit_id', 'date_time'])

sorted_control['time_spent_minutes'] = (
    sorted_control.groupby('visit_id')['date_time']
    .diff()
    .abs()
    .dt.total_seconds() / 60
)
sorted_control['time_spent_minutes']

In [ ]:
sorted_control.groupby('visit_id')['time_spent_minutes'].sum()
# Total Time per Visit

In [ ]:
sorted_control.groupby('process_step')['time_spent_minutes'].mean()
#. Average Time per Step