In [ ]:
import pandas as pd
df=pd.read_csv(r"C:\Users\prodd\Downloads\df_final_demo.txt")
df

In [ ]:
part1=pd.read_csv(r"C:\Users\prodd\Downloads\df_final_web_data_pt_1.txt")
part1

In [ ]:
part2=pd.read_csv(r"C:\Users\prodd\Downloads\df_final_web_data_pt_2.txt")
part2

In [ ]:
df_concated=pd.concat([part1,part2], ignore_index=True)
df_concated

In [ ]:
Variation=pd.read_csv(r"C:\Users\prodd\Downloads\df_final_experiment_clients.txt")
Variation

In [9]:
merged = pd.merge(df, df_concated, on='client_id', how='inner')
merged

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth,visitor_id,visit_id,process_step,date_time
0,836976,6.0,73.0,60.5,U,2.0,45105.30,6.0,9.0,427070339_1413275162,228976764_46825473280_96584,confirm,2017-04-02 11:51:13
1,836976,6.0,73.0,60.5,U,2.0,45105.30,6.0,9.0,427070339_1413275162,228976764_46825473280_96584,confirm,2017-04-02 11:47:50
2,836976,6.0,73.0,60.5,U,2.0,45105.30,6.0,9.0,427070339_1413275162,228976764_46825473280_96584,confirm,2017-04-02 11:46:45
3,836976,6.0,73.0,60.5,U,2.0,45105.30,6.0,9.0,427070339_1413275162,228976764_46825473280_96584,step_3,2017-04-02 11:23:08
4,836976,6.0,73.0,60.5,U,2.0,45105.30,6.0,9.0,427070339_1413275162,228976764_46825473280_96584,step_2,2017-04-02 11:22:24
...,...,...,...,...,...,...,...,...,...,...,...,...,...
449826,5602139,21.0,254.0,59.5,F,3.0,157498.73,7.0,7.0,962766819_57063135389,158544612_4105226940_43043,confirm,2017-04-05 11:48:02
449827,5602139,21.0,254.0,59.5,F,3.0,157498.73,7.0,7.0,962766819_57063135389,158544612_4105226940_43043,step_3,2017-04-05 11:44:07
449828,5602139,21.0,254.0,59.5,F,3.0,157498.73,7.0,7.0,962766819_57063135389,158544612_4105226940_43043,step_2,2017-04-05 11:43:10
449829,5602139,21.0,254.0,59.5,F,3.0,157498.73,7.0,7.0,962766819_57063135389,884309593_49820690623_654151,step_1,2017-04-05 11:41:32
449830,5602139,21.0,254.0,59.5,F,3.0,157498.73,7.0,7.0,962766819_57063135389,884309593_49820690623_654151,start,2017-04-05 11:41:04

In [10]:
full_df = pd.merge(merged, Variation, on='client_id', how='inner')
full_df

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth,visitor_id,visit_id,process_step,date_time,Variation
0,836976,6.0,73.0,60.5,U,2.0,45105.30,6.0,9.0,427070339_1413275162,228976764_46825473280_96584,confirm,2017-04-02 11:51:13,Test
1,836976,6.0,73.0,60.5,U,2.0,45105.30,6.0,9.0,427070339_1413275162,228976764_46825473280_96584,confirm,2017-04-02 11:47:50,Test
2,836976,6.0,73.0,60.5,U,2.0,45105.30,6.0,9.0,427070339_1413275162,228976764_46825473280_96584,confirm,2017-04-02 11:46:45,Test
3,836976,6.0,73.0,60.5,U,2.0,45105.30,6.0,9.0,427070339_1413275162,228976764_46825473280_96584,step_3,2017-04-02 11:23:08,Test
4,836976,6.0,73.0,60.5,U,2.0,45105.30,6.0,9.0,427070339_1413275162,228976764_46825473280_96584,step_2,2017-04-02 11:22:24,Test
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
449826,5602139,21.0,254.0,59.5,F,3.0,157498.73,7.0,7.0,962766819_57063135389,158544612_4105226940_43043,confirm,2017-04-05 11:48:02,NaN
449827,5602139,21.0,254.0,59.5,F,3.0,157498.73,7.0,7.0,962766819_57063135389,158544612_4105226940_43043,step_3,2017-04-05 11:44:07,NaN
449828,5602139,21.0,254.0,59.5,F,3.0,157498.73,7.0,7.0,962766819_57063135389,158544612_4105226940_43043,step_2,2017-04-05 11:43:10,NaN
449829,5602139,21.0,254.0,59.5,F,3.0,157498.73,7.0,7.0,962766819_57063135389,884309593_49820690623_654151,step_1,2017-04-05 11:41:32,NaN
449830,5602139,21.0,254.0,59.5,F,3.0,157498.73,7.0,7.0,962766819_57063135389,884309593_49820690623_654151,start,2017-04-05 11:41:04,NaN

In [11]:
full_df=full_df.dropna()

In [13]:
full_df.shape

(321195, 14)

In [14]:
full_df.isna().sum()

client_id           0
clnt_tenure_yr      0
clnt_tenure_mnth    0
clnt_age            0
gendr               0
num_accts           0
bal                 0
calls_6_mnth        0
logons_6_mnth       0
visitor_id          0
visit_id            0
process_step        0
date_time           0
Variation           0
dtype: int64

In [19]:
full_df = full_df[full_df["gendr"].isin(["M", "F"])]

In [15]:
primary_cilents=full_df.groupby('client_id').agg({'visit_id': 'count'}).sort_values(by='visit_id',ascending=False).head(10)
primary_cilents

           visit_id
client_id
2274658          90
1595223          81
5951379          81
1952790          80
3545814          72
465007           72
7733877          72
9638063          71
2313292          61
4167815          61

In [20]:
test_table=full_df[full_df['Variation'].str.lower() == 'test']
test_table

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth,visitor_id,visit_id,process_step,date_time,Variation
22,1562045,16.0,198.0,49.0,M,2.0,67454.65,3.0,6.0,391202328_71710993352,71954691_44810191073_495385,start,2017-04-06 19:03:46,Test
36,388801,30.0,361.0,57.5,M,5.0,522498.72,1.0,4.0,56607555_75044897582,247503697_11679931698_453228,confirm,2017-04-06 10:48:22,Test
37,388801,30.0,361.0,57.5,M,5.0,522498.72,1.0,4.0,56607555_75044897582,247503697_11679931698_453228,step_3,2017-04-06 10:45:09,Test
38,388801,30.0,361.0,57.5,M,5.0,522498.72,1.0,4.0,56607555_75044897582,247503697_11679931698_453228,step_2,2017-04-06 10:41:56,Test
39,388801,30.0,361.0,57.5,M,5.0,522498.72,1.0,4.0,56607555_75044897582,247503697_11679931698_453228,step_1,2017-04-06 10:39:23,Test
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
321304,7468138,18.0,222.0,61.0,F,3.0,209278.15,0.0,3.0,317123960_46820919455,769876461_30381166055_830233,step_2,2017-03-30 23:59:15,Test
321305,7468138,18.0,222.0,61.0,F,3.0,209278.15,0.0,3.0,317123960_46820919455,769876461_30381166055_830233,step_1,2017-03-30 23:58:51,Test
321306,7468138,18.0,222.0,61.0,F,3.0,209278.15,0.0,3.0,317123960_46820919455,769876461_30381166055_830233,start,2017-03-30 23:58:40,Test
321307,7468138,18.0,222.0,61.0,F,3.0,209278.15,0.0,3.0,317123960_46820919455,769876461_30381166055_830233,start,2017-03-30 23:55:11,Test
321308,7468138,18.0,222.0,61.0,F,3.0,209278.15,0.0,3.0,317123960_46820919455,769876461_30381166055_830233,start,2017-03-31 00:16:12,Test

In [21]:
control_table = full_df[full_df['Variation'].str.lower() == 'control']
control_table

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth,visitor_id,visit_id,process_step,date_time,Variation
23,5126305,12.0,145.0,33.0,F,2.0,103671.75,0.0,3.0,432077852_35036160885,942996157_39527225999_589383,start,2017-06-14 14:22:31,Control
41,285619,30.0,369.0,67.5,M,2.0,299388.72,3.0,6.0,667009768_32934260678,545534470_5635716155_93472,confirm,2017-03-29 11:57:25,Control
42,285619,30.0,369.0,67.5,M,2.0,299388.72,3.0,6.0,667009768_32934260678,545534470_5635716155_93472,step_3,2017-03-29 11:55:31,Control
43,285619,30.0,369.0,67.5,M,2.0,299388.72,3.0,6.0,667009768_32934260678,545534470_5635716155_93472,step_2,2017-03-29 11:55:27,Control
44,285619,30.0,369.0,67.5,M,2.0,299388.72,3.0,6.0,667009768_32934260678,545534470_5635716155_93472,step_3,2017-03-29 11:54:55,Control
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
321283,6967120,21.0,260.0,68.5,M,3.0,4279873.38,6.0,9.0,663474827_38847225720,923772865_74694577233_449836,confirm,2017-04-12 19:06:55,Control
321284,6967120,21.0,260.0,68.5,M,3.0,4279873.38,6.0,9.0,663474827_38847225720,923772865_74694577233_449836,step_3,2017-04-12 19:05:14,Control
321285,6967120,21.0,260.0,68.5,M,3.0,4279873.38,6.0,9.0,663474827_38847225720,923772865_74694577233_449836,step_2,2017-04-12 19:04:29,Control
321286,6967120,21.0,260.0,68.5,M,3.0,4279873.38,6.0,9.0,663474827_38847225720,923772865_74694577233_449836,step_1,2017-04-12 19:04:07,Control
321287,6967120,21.0,260.0,68.5,M,3.0,4279873.38,6.0,9.0,663474827_38847225720,923772865_74694577233_449836,start,2017-04-12 19:03:36,Control